services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: carboxylase_backend
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: carboxylase_frontend
    ports:
      - "127.0.0.1:18080:80"
    restart: unless-stopped
